name: 'Search Universities'
description: 'Search country and print universities'
inputs:
  country:
    description: 'Country name separated with + sign'
    required: true
    default: 'United+States'
runs:
  using: 'node16'
  main: 'dist/index.js'