name: Test custom GitHub Action

on:
  workflow_dispatch:
    inputs:
      test:
        description: Do you want to run?
        required: true
        default: 'Yes'

jobs:
  university_search_job:
    runs-on: ubuntu-latest
    name: A job to search by university
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: University search
        uses: ./
        id: test
        with:
          country: 'United States'
